/**
 * PDF Report Translations
 * Bilingual support for PDF report generation (EN/IT)
 */

export type ReportLanguage = 'en' | 'it';

export interface ReportTranslations {
  // Progress messages
  progress: {
    capturingCharts: string;
    generatingAiDiagnosis: string;
    savingPdf: string;
  };
  // Cover page
  cover: {
    title: string;
    period: string;
    address: string;
    brand: string;
    holding: string;
    region: string;
    generatedOn: string;
    currentKpis: string;
  };
  // KPI labels
  kpis: {
    temperature: string;
    co2: string;
    humidity: string;
    airQuality: string;
  };
  // Section headers
  sections: {
    energyDashboard: string;
    waterDashboard: string;
    airQualityDashboard: string;
    aiDiagnosis: string;
  };
  // Energy section
  energy: {
    consumptionChart: string;
    consumption: string;
    deviceChart: string;
    deviceConsumption: string;
    co2Emissions: string;
  };
  // Water section
  water: {
    consumptionChart: string;
    consumption: string;
    quality: string;
    leakDetection: string;
  };
  // Air quality section
  airQuality: {
    chart: string;
    co2TvocHistory: string;
    tempHumidity: string;
    particulates: string;
  };
  // Table headers
  tables: {
    device: string;
    consumptionKwh: string;
    category: string;
    zone: string;
    leakRate: string;
    status: string;
    detected: string;
    co2Kg: string;
    consumptionL: string;
  };
  // Status labels
  status: {
    ok: string;
    warning: string;
    critical: string;
  };
  // AI Diagnosis section
  aiSection: {
    badge: string;
    disclaimerLine1: string;
    disclaimerLine2: string;
  };
  // Footer
  footer: {
    page: string;
    of: string;
  };
}

const translations: Record<ReportLanguage, ReportTranslations> = {
  en: {
    progress: {
      capturingCharts: "Capturing charts...",
      generatingAiDiagnosis: "Generating AI energy diagnosis...",
      savingPdf: "Saving PDF...",
    },
    cover: {
      title: "Dashboard Report",
      period: "Period",
      address: "Address",
      brand: "Brand",
      holding: "Holding",
      region: "Region",
      generatedOn: "Generated on",
      currentKpis: "Current KPIs",
    },
    kpis: {
      temperature: "Temperature",
      co2: "CO₂",
      humidity: "Humidity",
      airQuality: "Air Quality",
    },
    sections: {
      energyDashboard: "📊 Energy Dashboard",
      waterDashboard: "💧 Water Dashboard",
      airQualityDashboard: "🌬️ Air Quality Dashboard",
      aiDiagnosis: "Feature Diagnosis",
    },
    energy: {
      consumptionChart: "Energy Consumption Chart",
      consumption: "Energy Consumption",
      deviceChart: "Device Consumption Chart",
      deviceConsumption: "Consumption by Device",
      co2Emissions: "CO₂ Emissions",
    },
    water: {
      consumptionChart: "Water Consumption Chart",
      consumption: "Water Consumption",
      quality: "Water Quality",
      leakDetection: "Leak Detection",
    },
    airQuality: {
      chart: "Air Quality Chart",
      co2TvocHistory: "CO₂ and TVOC History",
      tempHumidity: "Temperature and Humidity",
      particulates: "Particulates (PM2.5 / PM10)",
    },
    tables: {
      device: "Device",
      consumptionKwh: "Consumption (kWh)",
      category: "Category",
      zone: "Zone",
      leakRate: "Leak Rate (L/h)",
      status: "Status",
      detected: "Detected",
      co2Kg: "CO₂ (kg)",
      consumptionL: "Consumption (L)",
    },
    status: {
      ok: "✓ OK",
      warning: "⚠ Warning",
      critical: "⚠ Critical",
    },
    aiSection: {
      badge: "This analysis is powerd by FGB-AI",
      disclaimerLine1: "This diagnosis is generated by FGB-AI models and is for indicative purposes only.",
      disclaimerLine2: "For further validation please contatct our professional team at monitoring@fgb-studio.com.",
    },
    footer: {
      page: "Page",
      of: "of",
    },
  },
  it: {
    progress: {
      capturingCharts: "Acquisizione grafici...",
      generatingAiDiagnosis: "Generazione diagnosi energetica AI...",
      savingPdf: "Salvataggio PDF...",
    },
    cover: {
      title: "Report Dashboard",
      period: "Periodo",
      address: "Indirizzo",
      brand: "Brand",
      holding: "Holding",
      region: "Regione",
      generatedOn: "Generato il",
      currentKpis: "KPI Attuali",
    },
    kpis: {
      temperature: "Temperatura",
      co2: "CO₂",
      humidity: "Umidità",
      airQuality: "Qualità Aria",
    },
    sections: {
      energyDashboard: "📊 Dashboard Energia",
      waterDashboard: "💧 Dashboard Acqua",
      airQualityDashboard: "🌬️ Dashboard Qualità Aria",
      aiDiagnosis: "Diagnosi delle performances",
    },
    energy: {
      consumptionChart: "Grafico Consumi Energetici",
      consumption: "Consumi Energetici",
      deviceChart: "Grafico Consumi per Dispositivo",
      deviceConsumption: "Consumi per Dispositivo",
      co2Emissions: "Emissioni CO₂",
    },
    water: {
      consumptionChart: "Grafico Consumi Idrici",
      consumption: "Consumi Idrici",
      quality: "Qualità Acqua",
      leakDetection: "Rilevamento Perdite",
    },
    airQuality: {
      chart: "Grafico Qualità Aria",
      co2TvocHistory: "Storico CO₂ e TVOC",
      tempHumidity: "Temperatura e Umidità",
      particulates: "Particolato (PM2.5 / PM10)",
    },
    tables: {
      device: "Dispositivo",
      consumptionKwh: "Consumo (kWh)",
      category: "Categoria",
      zone: "Zona",
      leakRate: "Tasso Perdita (L/h)",
      status: "Stato",
      detected: "Rilevato",
      co2Kg: "CO₂ (kg)",
      consumptionL: "Consumo (L)",
    },
    status: {
      ok: "✓ OK",
      warning: "⚠ Attenzione",
      critical: "⚠ Critico",
    },
    aiSection: {
      badge: "Questa analisi è generata da FGB-AI",
      disclaimerLine1: "Questa diagnosi è generata dai modelli FGB-AI ed è solo a scopo indicativo",
      disclaimerLine2: "Per ulteriori verifiche, contatta il nostro team di professionisti all’indirizzo monitoring@fgb-studio.com",
    },
    footer: {
      page: "Pagina",
      of: "di",
    },
  },
};

export const getTranslations = (lang: ReportLanguage): ReportTranslations => {
  return translations[lang];
};

export const getDateLocale = async (lang: ReportLanguage) => {
  if (lang === 'it') {
    const { it } = await import('date-fns/locale');
    return it;
  }
  const { enUS } = await import('date-fns/locale');
  return enUS;
};
