/**
 * PDF Report Translations
 * Multilingual support for PDF report generation (EN/IT/FR/ES/ZH)
 */

export type ReportLanguage = 'en' | 'it' | 'fr' | 'es' | 'zh';

export interface ReportTranslations {
  progress: { capturingCharts: string; generatingAiDiagnosis: string; savingPdf: string; };
  cover: { title: string; period: string; address: string; brand: string; holding: string; region: string; generatedOn: string; currentKpis: string; };
  kpis: { temperature: string; co2: string; humidity: string; airQuality: string; };
  sections: { energyDashboard: string; waterDashboard: string; airQualityDashboard: string; aiDiagnosis: string; };
  energy: { consumptionChart: string; consumption: string; deviceChart: string; deviceConsumption: string; co2Emissions: string; };
  water: { consumptionChart: string; consumption: string; quality: string; leakDetection: string; };
  airQuality: { chart: string; co2TvocHistory: string; tempHumidity: string; particulates: string; };
  tables: { device: string; consumptionKwh: string; category: string; zone: string; leakRate: string; status: string; detected: string; co2Kg: string; consumptionL: string; };
  status: { ok: string; warning: string; critical: string; };
  aiSection: { badge: string; disclaimerLine1: string; disclaimerLine2: string; };
  footer: { page: string; of: string; };
}

const translations: Record<ReportLanguage, ReportTranslations> = {
  en: {
    progress: { capturingCharts: "Capturing charts...", generatingAiDiagnosis: "Generating AI energy diagnosis...", savingPdf: "Saving PDF..." },
    cover: { title: "Dashboard Report", period: "Period", address: "Address", brand: "Brand", holding: "Holding", region: "Region", generatedOn: "Generated on", currentKpis: "Current KPIs" },
    kpis: { temperature: "Temperature", co2: "CO₂", humidity: "Humidity", airQuality: "Air Quality" },
    sections: { energyDashboard: "📊 Energy Dashboard", waterDashboard: "💧 Water Dashboard", airQualityDashboard: "🌬️ Air Quality Dashboard", aiDiagnosis: "Feature Diagnosis" },
    energy: { consumptionChart: "Energy Consumption Chart", consumption: "Energy Consumption", deviceChart: "Device Consumption Chart", deviceConsumption: "Consumption by Device", co2Emissions: "CO₂ Emissions" },
    water: { consumptionChart: "Water Consumption Chart", consumption: "Water Consumption", quality: "Water Quality", leakDetection: "Leak Detection" },
    airQuality: { chart: "Air Quality Chart", co2TvocHistory: "CO₂ and TVOC History", tempHumidity: "Temperature and Humidity", particulates: "Particulates (PM2.5 / PM10)" },
    tables: { device: "Device", consumptionKwh: "Consumption (kWh)", category: "Category", zone: "Zone", leakRate: "Leak Rate (L/h)", status: "Status", detected: "Detected", co2Kg: "CO₂ (kg)", consumptionL: "Consumption (L)" },
    status: { ok: "✓ OK", warning: "⚠ Warning", critical: "⚠ Critical" },
    aiSection: { badge: "This analysis is powerd by FGB-AI", disclaimerLine1: "This diagnosis is generated by FGB-AI models and is for indicative purposes only.", disclaimerLine2: "For further validation please contatct our professional team at monitoring@fgb-studio.com." },
    footer: { page: "Page", of: "of" },
  },
  it: {
    progress: { capturingCharts: "Acquisizione grafici...", generatingAiDiagnosis: "Generazione diagnosi energetica AI...", savingPdf: "Salvataggio PDF..." },
    cover: { title: "Report Dashboard", period: "Periodo", address: "Indirizzo", brand: "Brand", holding: "Holding", region: "Regione", generatedOn: "Generato il", currentKpis: "KPI Attuali" },
    kpis: { temperature: "Temperatura", co2: "CO₂", humidity: "Umidità", airQuality: "Qualità Aria" },
    sections: { energyDashboard: "📊 Dashboard Energia", waterDashboard: "💧 Dashboard Acqua", airQualityDashboard: "🌬️ Dashboard Qualità Aria", aiDiagnosis: "Diagnosi delle performances" },
    energy: { consumptionChart: "Grafico Consumi Energetici", consumption: "Consumi Energetici", deviceChart: "Grafico Consumi per Dispositivo", deviceConsumption: "Consumi per Dispositivo", co2Emissions: "Emissioni CO₂" },
    water: { consumptionChart: "Grafico Consumi Idrici", consumption: "Consumi Idrici", quality: "Qualità Acqua", leakDetection: "Rilevamento Perdite" },
    airQuality: { chart: "Grafico Qualità Aria", co2TvocHistory: "Storico CO₂ e TVOC", tempHumidity: "Temperatura e Umidità", particulates: "Particolato (PM2.5 / PM10)" },
    tables: { device: "Dispositivo", consumptionKwh: "Consumo (kWh)", category: "Categoria", zone: "Zona", leakRate: "Tasso Perdita (L/h)", status: "Stato", detected: "Rilevato", co2Kg: "CO₂ (kg)", consumptionL: "Consumo (L)" },
    status: { ok: "✓ OK", warning: "⚠ Attenzione", critical: "⚠ Critico" },
    aiSection: { badge: "Questa analisi è generata da FGB-AI", disclaimerLine1: "Questa diagnosi è generata dai modelli FGB-AI ed è solo a scopo indicativo", disclaimerLine2: "Per ulteriori verifiche, contatta il nostro team di professionisti all'indirizzo monitoring@fgb-studio.com" },
    footer: { page: "Pagina", of: "di" },
  },
  fr: {
    progress: { capturingCharts: "Capture des graphiques...", generatingAiDiagnosis: "Génération du diagnostic énergétique IA...", savingPdf: "Enregistrement du PDF..." },
    cover: { title: "Rapport du tableau de bord", period: "Période", address: "Adresse", brand: "Marque", holding: "Groupe", region: "Région", generatedOn: "Généré le", currentKpis: "KPI actuels" },
    kpis: { temperature: "Température", co2: "CO₂", humidity: "Humidité", airQuality: "Qualité de l'air" },
    sections: { energyDashboard: "📊 Tableau de bord Énergie", waterDashboard: "💧 Tableau de bord Eau", airQualityDashboard: "🌬️ Tableau de bord Qualité de l'air", aiDiagnosis: "Diagnostic des performances" },
    energy: { consumptionChart: "Graphique de consommation énergétique", consumption: "Consommation énergétique", deviceChart: "Graphique de consommation par appareil", deviceConsumption: "Consommation par appareil", co2Emissions: "Émissions de CO₂" },
    water: { consumptionChart: "Graphique de consommation d'eau", consumption: "Consommation d'eau", quality: "Qualité de l'eau", leakDetection: "Détection de fuites" },
    airQuality: { chart: "Graphique qualité de l'air", co2TvocHistory: "Historique CO₂ et TVOC", tempHumidity: "Température et Humidité", particulates: "Particules (PM2.5 / PM10)" },
    tables: { device: "Appareil", consumptionKwh: "Consommation (kWh)", category: "Catégorie", zone: "Zone", leakRate: "Taux de fuite (L/h)", status: "Statut", detected: "Détecté", co2Kg: "CO₂ (kg)", consumptionL: "Consommation (L)" },
    status: { ok: "✓ OK", warning: "⚠ Avertissement", critical: "⚠ Critique" },
    aiSection: { badge: "Cette analyse est générée par FGB-AI", disclaimerLine1: "Ce diagnostic est généré par les modèles FGB-AI et est fourni à titre indicatif uniquement.", disclaimerLine2: "Pour une validation complémentaire, contactez notre équipe professionnelle à monitoring@fgb-studio.com." },
    footer: { page: "Page", of: "de" },
  },
  es: {
    progress: { capturingCharts: "Capturando gráficos...", generatingAiDiagnosis: "Generando diagnóstico energético IA...", savingPdf: "Guardando PDF..." },
    cover: { title: "Informe del panel", period: "Período", address: "Dirección", brand: "Marca", holding: "Grupo", region: "Región", generatedOn: "Generado el", currentKpis: "KPI actuales" },
    kpis: { temperature: "Temperatura", co2: "CO₂", humidity: "Humedad", airQuality: "Calidad del aire" },
    sections: { energyDashboard: "📊 Panel de Energía", waterDashboard: "💧 Panel de Agua", airQualityDashboard: "🌬️ Panel de Calidad del Aire", aiDiagnosis: "Diagnóstico de rendimiento" },
    energy: { consumptionChart: "Gráfico de consumo energético", consumption: "Consumo energético", deviceChart: "Gráfico de consumo por dispositivo", deviceConsumption: "Consumo por dispositivo", co2Emissions: "Emisiones de CO₂" },
    water: { consumptionChart: "Gráfico de consumo de agua", consumption: "Consumo de agua", quality: "Calidad del agua", leakDetection: "Detección de fugas" },
    airQuality: { chart: "Gráfico de calidad del aire", co2TvocHistory: "Historial de CO₂ y TVOC", tempHumidity: "Temperatura y Humedad", particulates: "Partículas (PM2.5 / PM10)" },
    tables: { device: "Dispositivo", consumptionKwh: "Consumo (kWh)", category: "Categoría", zone: "Zona", leakRate: "Tasa de fuga (L/h)", status: "Estado", detected: "Detectado", co2Kg: "CO₂ (kg)", consumptionL: "Consumo (L)" },
    status: { ok: "✓ OK", warning: "⚠ Advertencia", critical: "⚠ Crítico" },
    aiSection: { badge: "Este análisis es generado por FGB-AI", disclaimerLine1: "Este diagnóstico es generado por los modelos FGB-AI y tiene fines meramente indicativos.", disclaimerLine2: "Para una validación adicional, contacte a nuestro equipo profesional en monitoring@fgb-studio.com." },
    footer: { page: "Página", of: "de" },
  },
  zh: {
    progress: { capturingCharts: "正在捕获图表...", generatingAiDiagnosis: "正在生成 AI 能源诊断...", savingPdf: "正在保存 PDF..." },
    cover: { title: "仪表板报告", period: "期间", address: "地址", brand: "品牌", holding: "集团", region: "区域", generatedOn: "生成日期", currentKpis: "当前 KPI" },
    kpis: { temperature: "温度", co2: "CO₂", humidity: "湿度", airQuality: "空气质量" },
    sections: { energyDashboard: "📊 能源仪表板", waterDashboard: "💧 水务仪表板", airQualityDashboard: "🌬️ 空气质量仪表板", aiDiagnosis: "性能诊断" },
    energy: { consumptionChart: "能耗图表", consumption: "能耗", deviceChart: "设备能耗图表", deviceConsumption: "按设备能耗", co2Emissions: "CO₂ 排放" },
    water: { consumptionChart: "用水量图表", consumption: "用水量", quality: "水质", leakDetection: "漏水检测" },
    airQuality: { chart: "空气质量图表", co2TvocHistory: "CO₂ 与 TVOC 历史", tempHumidity: "温度与湿度", particulates: "颗粒物 (PM2.5 / PM10)" },
    tables: { device: "设备", consumptionKwh: "能耗 (kWh)", category: "类别", zone: "区域", leakRate: "泄漏率 (L/h)", status: "状态", detected: "检测时间", co2Kg: "CO₂ (kg)", consumptionL: "消耗量 (L)" },
    status: { ok: "✓ 正常", warning: "⚠ 警告", critical: "⚠ 严重" },
    aiSection: { badge: "此分析由 FGB-AI 提供支持", disclaimerLine1: "此诊断由 FGB-AI 模型生成，仅供参考。", disclaimerLine2: "如需进一步验证，请联系我们的专业团队：monitoring@fgb-studio.com。" },
    footer: { page: "第", of: "页，共" },
  },
};

export const getTranslations = (lang: ReportLanguage): ReportTranslations => {
  return translations[lang];
};

export const getDateLocale = async (lang: ReportLanguage) => {
  if (lang === 'it') { const { it } = await import('date-fns/locale'); return it; }
  if (lang === 'fr') { const { fr } = await import('date-fns/locale'); return fr; }
  if (lang === 'es') { const { es } = await import('date-fns/locale'); return es; }
  if (lang === 'zh') { const { zhCN } = await import('date-fns/locale'); return zhCN; }
  const { enUS } = await import('date-fns/locale'); return enUS;
};
